### ISSUE TITLE
support node 18

### ISSUE THREAD

**Issue by kirilligum** [afa7789/gov_deployer#2]
could you add support for 18 please? 

 ~/try> git clone https://github.com/afa7789/gov_deployer.git && cd gov_deployer

Cloning into 'gov_deployer'...
remote: Enumerating objects: 563, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 563 (delta 55), reused 66 (delta 25), pack-reused 458
Receiving objects: 100% (563/563), 1.25 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (358/358), done.

 ~/t/gov_deployer (master)> yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning ethereum-waffle > @ethereum-waffle/provider > ganache-core > patch-package > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[2/4] Fetching packages...
error hardhat@2.9.9: The engine "node" is incompatible with this module. Expected version "^12.0.0 || ^14.0.0 || ^16.0.0". Got "18.12.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by afa7789** [comment]
@kirilligum current hardhat version we are using is limited to those

you can use NVM to change the version of your node locally.
